site_name: Aprendia Docs
site_url: https://ICHEJA-PROJECT/aprendIA-docs
theme:
  name: material
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Inicio: index.md
  - Misión y Visión: mision-vision.md
  - Contribuir: contributing.md
  - Código de Conducta: code-of-conduct.md
  - Proyectos:
      - Alfabetización: proyectos/alfabetizacion.md
      - Terrarios Inteligentes: proyectos/terrarios.md
      - Juegos Educativos: proyectos/juegos.md
  - Guías Técnicas:
      - Instalación: guias/instalacion.md
      - Arquitectura: guias/arquitectura.md
      - CI/CD: guias/ci-cd.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
