site_name: Aprendia Docs
site_url: https://icheja-project.github.io/aprendIA-docs/
theme:
  name: material
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Inicio: index.md
  - Proyectos:
      - Alfabetización: proyectos/alfabetizacion.md
  - Guías Técnicas:
      - Arquitectura backend: guias/arquitectura-backend.md
      - Arquitectura mobile: guias/arquitectura-mobile.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
